In [1]:
import os
import networkx as nx
import numpy as np
import pandas as pd
import math
import pyflagser

In [2]:
G=nx.read_gml("bus37Ex.gml")

In [3]:
G.nodes()

NodeView(('sourcebus', '799', '709', '775', '701', '702', '705', '713', '703', '727', '730', '704', '714', '720', '742', '712', '706', '725', '707', '724', '722', '708', '733', '732', '731', '710', '735', '736', '711', '741', '740', '718', '744', '734', '737', '738', '728', '729', '799r'))

In [4]:
G.edges

EdgeView([('sourcebus', '799'), ('799', '799r'), ('709', '775'), ('709', '731'), ('709', '708'), ('709', '730'), ('701', '702'), ('701', '799r'), ('702', '705'), ('702', '713'), ('702', '703'), ('705', '742'), ('705', '712'), ('713', '704'), ('703', '727'), ('703', '730'), ('727', '744'), ('704', '714'), ('704', '720'), ('714', '718'), ('720', '707'), ('720', '706'), ('706', '725'), ('707', '724'), ('707', '722'), ('708', '733'), ('708', '732'), ('733', '734'), ('710', '735'), ('710', '736'), ('710', '734'), ('711', '741'), ('711', '740'), ('711', '738'), ('744', '728'), ('744', '729'), ('734', '737'), ('737', '738')])

In [6]:
G

In [18]:
df = nx.to_pandas_adjacency(G, dtype=int)
df

sourcebus  799  709  775  701  702  705  713  703  727  ...  741  \
sourcebus          0    1    0    0    0    0    0    0    0    0  ...    0   
799                1    0    0    0    0    0    0    0    0    0  ...    0   
709                0    0    0    1    0    0    0    0    0    0  ...    0   
775                0    0    1    0    0    0    0    0    0    0  ...    0   
701                0    0    0    0    0    1    0    0    0    0  ...    0   
702                0    0    0    0    1    0    1    1    1    0  ...    0   
705                0    0    0    0    0    1    0    0    0    0  ...    0   
713                0    0    0    0    0    1    0    0    0    0  ...    0   
703                0    0    0    0    0    1    0    0    0    1  ...    0   
727                0    0    0    0    0    0    0    0    1    0  ...    0   
730                0    0    1    0    0    0    0    0    1    0  ...    0   
704                0    0    0    0    0    0    0    1    0    0  ...    0   
714                0    0    0    0    0    0    0    0    0    0  ...    0   
720                0    0    0    0    0    0    0    0    0    0  ...    0   
742                0    0    0    0    0    0    1    0    0    0  ...    0   
712                0    0    0    0    0    0    1    0    0    0  ...    0   
706                0    0    0    0    0    0    0    0    0    0  ...    0   
725                0    0    0    0    0    0    0    0    0    0  ...    0   
707                0    0    0    0    0    0    0    0    0    0  ...    0   
724                0    0    0    0    0    0    0    0    0    0  ...    0   
722                0    0    0    0    0    0    0    0    0    0  ...    0   
708                0    0    1    0    0    0    0    0    0    0  ...    0   
733                0    0    0    0    0    0    0    0    0    0  ...    0   
732                0    0    0    0    0    0    0    0    0    0  ...    0   
731                0    0    1    0    0    0    0    0    0    0  ...    0   
710                0    0    0    0    0    0    0    0    0    0  ...    0   
735                0    0    0    0    0    0    0    0    0    0  ...    0   
736                0    0    0    0    0    0    0    0    0    0  ...    0   
711                0    0    0    0    0    0    0    0    0    0  ...    1   
741                0    0    0    0    0    0    0    0    0    0  ...    0   
740                0    0    0    0    0    0    0    0    0    0  ...    0   
718                0    0    0    0    0    0    0    0    0    0  ...    0   
744                0    0    0    0    0    0    0    0    0    1  ...    0   
734                0    0    0    0    0    0    0    0    0    0  ...    0   
737                0    0    0    0    0    0    0    0    0    0  ...    0   
738                0    0    0    0    0    0    0    0    0    0  ...    0   
728                0    0    0    0    0    0    0    0    0    0  ...    0   
729                0    0    0    0    0    0    0    0    0    0  ...    0   
799r               0    1    0    0    1    0    0    0    0    0  ...    0   

           740  718  744  734  737  738  728  729  799r  
sourcebus    0    0    0    0    0    0    0    0     0  
799          0    0    0    0    0    0    0    0     1  
709          0    0    0    0    0    0    0    0     0  
775          0    0    0    0    0    0    0    0     0  
701          0    0    0    0    0    0    0    0     1  
702          0    0    0    0    0    0    0    0     0  
705          0    0    0    0    0    0    0    0     0  
713          0    0    0    0    0    0    0    0     0  
703          0    0    0    0    0    0    0    0     0  
727          0    0    1    0    0    0    0    0     0  
730          0    0    0    0    0    0    0    0     0  
704          0    0    0    0    0    0    0    0     0  
714          0    1    0    0    0    0    0    0     0  
720          0    0    0    0    0    

In [5]:
A = nx.to_numpy_array(G)
print(A)

[[0. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [29]:
print(sum(sum(A))/2)

38.0


In [6]:
N=list(G.nodes)
print(N)
print(len(N))

['sourcebus', '799', '709', '775', '701', '702', '705', '713', '703', '727', '730', '704', '714', '720', '742', '712', '706', '725', '707', '724', '722', '708', '733', '732', '731', '710', '735', '736', '711', '741', '740', '718', '744', '734', '737', '738', '728', '729', '799r']
39


In [7]:
E=list(G.edges)
print(E)

[('sourcebus', '799'), ('799', '799r'), ('709', '775'), ('709', '731'), ('709', '708'), ('709', '730'), ('701', '702'), ('701', '799r'), ('702', '705'), ('702', '713'), ('702', '703'), ('705', '742'), ('705', '712'), ('713', '704'), ('703', '727'), ('703', '730'), ('727', '744'), ('704', '714'), ('704', '720'), ('714', '718'), ('720', '707'), ('720', '706'), ('706', '725'), ('707', '724'), ('707', '722'), ('708', '733'), ('708', '732'), ('733', '734'), ('710', '735'), ('710', '736'), ('710', '734'), ('711', '741'), ('711', '740'), ('711', '738'), ('744', '728'), ('744', '729'), ('734', '737'), ('737', '738')]


In [9]:
import pickle
with open('PartialObservdata.pkl', 'rb') as f:
    POData = pickle.load(f)
N_Senario=len(POData)
print(N_Senario)

1001


In [10]:
print(len(POData))
POData[0]

1001


{'Scenario': 0,
 'Edges failed': [],
 'TimeOutage': 0,
 'Bus PDemand': {'sourcebus': 0,
  '799': 0,
  '709': 0,
  '775': 0,
  '701': 630.0,
  '702': 0,
  '705': 0,
  '713': 85.0,
  '703': 0,
  '727': 42.0,
  '730': 85.0,
  '704': 0,
  '714': 38.0,
  '720': 85.0,
  '742': 93.0,
  '712': 85.0,
  '706': 0,
  '725': 42.0,
  '707': 0,
  '724': 42.0,
  '722': 161.0,
  '708': 0,
  '733': 85.0,
  '732': 42.0,
  '731': 85.0,
  '710': 0,
  '735': 85.0,
  '736': 42.0,
  '711': 0,
  '741': 42.0,
  '740': 85.0,
  '718': 85.0,
  '744': 42.0,
  '734': 42.0,
  '737': 140.0,
  '738': 126.0,
  '728': 126.0,
  '729': 42.0,
  '799r': 0},
 'Bus Voltages': {'sourcebus': array([0.99998671, 0.99999068, 0.99999031]),
  '799': array([0.87103023, 1.02462632, 0.90414322]),
  '709': array([nan, nan, nan]),
  '775': array([0.95000695, 0.99885309, 0.98397429]),
  '701': array([0.97363201, 1.01470776, 1.00050347]),
  '702': array([nan, nan, nan]),
  '705': array([nan, nan, nan]),
  '713': array([0.96390686, 1.0073767

In [11]:
AverageVoltage=[]
def Average(lst):
    return sum(lst) / len(lst)
Voltage=POData[0]["Bus Voltages"]
for x, y in Voltage.items():
    AverageVoltage.append(Average(list(y)))
print(AverageVoltage)
AverageVoltage = [-1 if math.isnan(x) else x for x in AverageVoltage]
print(AverageVoltage)

[0.9999892329710348, 0.9332665897883389, nan, 0.9776114416792622, 0.9962810786267132, nan, nan, 0.9875777785949996, nan, nan, nan, nan, 0.985391650875652, 0.9831804113631302, 0.9877052080525924, 0.9878438234644067, nan, nan, 0.9803046560365619, nan, 0.9800072830262644, 0.9757004571163487, nan, nan, 0.9771610604219606, 0.9701305107418645, 0.9698604523770956, nan, nan, nan, 0.9673943147349924, nan, nan, 0.9711702269060213, 0.9690237578185519, nan, 0.981601224868176, nan, 1.0093975092889806]
[0.9999892329710348, 0.9332665897883389, -1, 0.9776114416792622, 0.9962810786267132, -1, -1, 0.9875777785949996, -1, -1, -1, -1, 0.985391650875652, 0.9831804113631302, 0.9877052080525924, 0.9878438234644067, -1, -1, 0.9803046560365619, -1, 0.9800072830262644, 0.9757004571163487, -1, -1, 0.9771610604219606, 0.9701305107418645, 0.9698604523770956, -1, -1, -1, 0.9673943147349924, -1, -1, 0.9711702269060213, 0.9690237578185519, -1, 0.981601224868176, -1, 1.0093975092889806]


In [61]:

BranchFlow=[]
Bflow=POData[2]["BranchFlow"]
for x, y in Bflow.items():
    BranchFlow.append(y)
print(BranchFlow)

BranchFlow = [-1 if math.isnan(x) else x for x in BranchFlow]
print(BranchFlow)

[0.0, 0.0, nan, 7.420312847512529e-69, 2.737452144781099e-68, nan, 2.14533833239555e-69, nan, nan, nan, nan, 8.551904187186977e-69, nan, 1.7122845520549117e-68, 1.3522288787438937e-68, nan, nan, 1.0814400731243844e-68, 1.7158225740512712e-68, 7.993215776075588e-69, nan, 4.577534053443768e-69, nan, nan, nan, nan, 2.1641147798567644e-69, 2.0652604255251956e-68, nan, nan, 8.792719258309333e-69, nan, 3.822814319583701e-69, 8.777990588786537e-69, 8.510488931455142e-69, nan, 2.843723968841173e-68, nan]
[0.0, 0.0, -1, 7.420312847512529e-69, 2.737452144781099e-68, -1, 2.14533833239555e-69, -1, -1, -1, -1, 8.551904187186977e-69, -1, 1.7122845520549117e-68, 1.3522288787438937e-68, -1, -1, 1.0814400731243844e-68, 1.7158225740512712e-68, 7.993215776075588e-69, -1, 4.577534053443768e-69, -1, -1, -1, -1, 2.1641147798567644e-69, 2.0652604255251956e-68, -1, -1, 8.792719258309333e-69, -1, 3.822814319583701e-69, 8.777990588786537e-69, 8.510488931455142e-69, -1, 2.843723968841173e-68, -1]


In [42]:
F_voltage=[0.99,0.98,0.97,0.96,0.95,0.94,0.93,0.90,0.85,0.80,0.75,0,-1]

In [72]:
F_Flow=[200,175,150,125,100,75,50,30,15,10,0,-1]

p=len(F_voltage)
q=len(F_Flow)
print(p)
print(q)
print(p*q)

13
12
156


In [15]:
Class=[]
for i in range(300):
    Class.append(POData[i]["NetOutage"])
#print(Class)
i=0
l=0
m=0
while i < len(Class):
    if Class[i] == 'No':
        l=l+1
        Class[i] = 0
    if Class[i] == 'Yes':
        m=m+1
        Class[i] = 1
    i += 1
#print(Class)
print(l)
print(m)

204
96


In [24]:
list_b0=[]
list_b1=[]
N_Senario=300
for k in range(N_Senario):
    print("\rProcessing file {} ({}%)".format(k, 100*k//(N_Senario-1)), end='', flush=True)
    AverageVoltage=[]
    Voltage=POData[k]["Bus Voltages"]
    for x, y in Voltage.items():
        AverageVoltage.append(Average(list(y)))
    AverageVoltage = [-1 if math.isnan(x) else x for x in AverageVoltage]
    #print(AverageVoltage)
    BranchFlow=[]
    Bflow=POData[k]["BranchFlow"]
    for x, y in Bflow.items():
        BranchFlow.append(y)
    #print(BranchFlow)
    BranchFlow = [-1 if math.isnan(x) else x for x in BranchFlow]
    #print(BranchFlow)
    b0_points=[]
    b1_points=[]
    for p in range(len(F_voltage)):
        for q in range(len(F_Flow)):
            n_active = np.where(np.array(AverageVoltage) > F_voltage[p])[0].tolist()
            indices = np.where(np.array(BranchFlow) > F_Flow[q])[0].tolist()
           # n_active=[]
            #for r in range(39):
             #   if AverageVoltage[r]>= F_voltage[p]:
              #      n_active.append(int(r))
            #for s in range(38):
             #   if BranchFlow[s]>=F_Flow[q]:
            for s in indices:
                n_active.append(int(N.index(E[s][0])))
                n_active.append(int(N.index(E[s][1])))
            Active_node=np.unique(n_active)
            #print(Active_node)
            b=A[Active_node,:][:,Active_node]
            my_flag=pyflagser.flagser_unweighted(b, min_dimension=0, max_dimension=2, directed=False, coeff=2, approximation=None)
            x = my_flag["betti"]
            #print(x[0])
            #x_points.append(unique_list[k])
            b0_points.append(x[0])
            b1_points.append(x[1])
            #print(b)
            #print(x_points)
            n_active.clear()
    #print(b0_points)
    list_b0.append(b0_points)
    list_b1.append(b1_points)


Processing file 299 (100%)

In [25]:
print(list_b0)

[[2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 2, 2, 7, 7, 7, 7, 7, 8, 6, 6, 5, 3, 2, 2, 11, 11, 11, 11, 11, 8, 6, 6, 5, 3, 2, 2, 12, 12, 12, 12, 12, 9, 7, 7, 5, 3, 2, 2, 12, 12, 12, 12, 12, 9, 7, 7, 5, 3, 2, 2, 12, 12, 12, 12, 12, 9, 7, 7, 5, 3, 2, 2, 11, 11, 11, 11, 11, 8, 6, 6, 4, 2, 2, 2, 11, 11, 11, 11, 11, 8, 6, 6, 4, 2, 2, 2, 11, 11, 11, 11, 11, 8, 6, 6, 4, 2, 2, 2, 11, 11, 11, 11, 11, 8, 6, 6, 4, 2, 2, 2, 11, 11, 11, 11, 11, 8, 6, 6, 4, 2, 2, 2, 11, 11, 11, 11, 11, 8, 6, 6, 4, 2, 2, 2, 11, 11, 11, 11, 11, 8, 6, 6, 4, 2, 2, 2], [13, 12, 12, 12, 12, 12, 9, 7, 7, 3, 2, 2, 13, 12, 12, 12, 12, 12, 9, 7, 7, 3, 2, 2, 13, 12, 12, 12, 12, 12, 9, 7, 7, 3, 2, 2, 13, 12, 12, 12, 12, 12, 9, 7, 7, 3, 2, 2, 12, 11, 11, 11, 11, 11, 8, 6, 6, 2, 2, 2, 12, 11, 11, 11, 11, 11, 8, 6, 6, 2, 2, 2, 12, 11, 11, 11, 11, 11, 8, 6, 6, 2, 2, 2, 12, 11, 11, 11, 11, 11, 8, 6, 6, 2, 2, 2, 12, 11, 11, 11, 11, 11, 8, 6, 6, 2, 2, 2, 12, 11, 11, 11, 11, 11, 8, 6, 6, 2, 2, 2, 12, 11, 11, 11, 11, 11, 8, 6, 6, 2, 2, 2, 12, 11, 11,

In [75]:
x =np.array(list_b0)
x1 =np.array(list_b1)
n=len(list_b0[0])
print(n)
Feture=[]
for i in range(p*q):
    Feture.append("{}".format(i))
#Feture=list(range(9,17))
data = pd.DataFrame(x, columns =Feture) 
data.insert(loc=p*q,column='Class',value=Class)
data.head(10)

156


0   1   2   3   4   5  6  7  8  9  ...  147  148  149  150  151  152  153  \
0   2   2   2   2   2   3  3  3  3  3  ...   11   11    8    6    6    4    2   
1  13  12  12  12  12  12  9  7  7  3  ...   11   11   11    8    6    6    2   
2   1   1   1   1   1   1  1  1  1  1  ...   12   12   12   12   12   12   12   
3  13  12  12  12  12  12  9  7  7  3  ...   11   11   11    8    6    6    2   
4   4   4   4   4   4   5  5  5  5  3  ...   11   11    8    6    6    4    2   
5  13  12  12  12  12  12  9  7  7  3  ...   11   11   11    8    6    6    2   
6   7   7   7   7   7   8  8  6  5  3  ...   11   11    8    8    6    4    2   
7  13  12  12  12  12  12  9  7  7  3  ...   11   11   11    8    6    6    2   
8  12  12  12  11  11  11  9  6  6  5  ...   11   11   11    9    6    6    5   
9  13  12  12  12  12  12  9  7  7  3  ...   11   11   11    8    6    6    2   

   154  155  Class  
0    2    2      0  
1    2    2      0  
2    2    2      1  
3    2    2      0  
4    2    2      1  
5    2    2      0  
6    2    2      1  
7    2    2      0  
8    2    2      1  
9    2    2      0  

[10 rows x 157 columns]

In [37]:
Vlist_b0=[]
Vlist_b1=[]
N_Senario=300
for k in range(N_Senario):
    print("\rProcessing file {} ({}%)".format(k, 100*k//(N_Senario-1)), end='', flush=True)
    AverageVoltage=[]
    Voltage=POData[k]["Bus Voltages"]
    for x, y in Voltage.items():
        AverageVoltage.append(Average(list(y)))
    AverageVoltage = [-1 if math.isnan(x) else x for x in AverageVoltage]
    b0_points=[]
    b1_points=[]
    for p in range(len(F_voltage)):
        n_active = np.where(np.array(AverageVoltage) > F_voltage[p])[0].tolist()
        Active_node=np.unique(n_active)
            #print(Active_node)
        b=A[Active_node,:][:,Active_node]
        my_flag=pyflagser.flagser_unweighted(b, min_dimension=0, max_dimension=2, directed=False, coeff=2, approximation=None)
        x = my_flag["betti"]
            #print(x[0])
            #x_points.append(unique_list[k])
        b0_points.append(x[0])
        b1_points.append(x[1])
            #print(b)
            #print(x_points)
        n_active.clear()
    #print(b0_points)
    Vlist_b0.append(b0_points)
    Vlist_b1.append(b1_points)

Processing file 299 (100%)

In [47]:
Vx =np.array(Vlist_b0)
Vx1 =np.array(Vlist_b1)
n=len(Vlist_b0[0])
print(p)
Feture=[]
for i in range(p):
    Feture.append("{}".format(i))
#Feture=list(range(9,17))
Vdata = pd.DataFrame(Vx, columns =Feture) 
Vdata.insert(loc=p,column='Class',value=Class)
Vdata.head(10)

13


0   1   2   3   4   5   6   7   8   9  10  11  12  Class
0   2   8  12  13  13  13  12  12  12  12  12  12  12      0
1  13  13  13  13  12  12  12  12  12  12  12  12  12      0
2   1   1   1   1   1   1   1   1   1   1   1  12  12      1
3  13  13  13  13  12  12  12  12  12  12  12  12  12      0
4   5  10  13  13  13  13  12  12  12  12  12  12  12      1
5  13  13  13  13  12  12  12  12  12  12  12  12  12      0
6   8  12  13  13  13  12  12  12  12  12  12  12  12      1
7  13  13  13  13  12  12  12  12  12  12  12  12  12      0
8  12  12  12  11  11  11  11  11  11  11  11  12  12      1
9  13  13  13  13  12  12  12  12  12  12  12  12  12      0

In [70]:
Flist_b0=[]
Flist_b1=[]
N_Senario=300
for k in range(N_Senario):
    print("\rProcessing file {} ({}%)".format(k, 100*k//(N_Senario-1)), end='', flush=True)
    BranchFlow=[]
    Bflow=POData[k]["BranchFlow"]
    for x, y in Bflow.items():
        BranchFlow.append(y)
    #print(BranchFlow)
    BranchFlow = [-1 if math.isnan(x) else x for x in BranchFlow]
    #print(BranchFlow)
    b0_points=[]
    b1_points=[]

    for q in range(len(F_Flow)):
        indices = np.where(np.array(BranchFlow) > F_Flow[q])[0].tolist()

        for s in indices:
            n_active.append(int(N.index(E[s][0])))
            n_active.append(int(N.index(E[s][1])))
        Active_node=np.unique(n_active)
        if (len(Active_node)==0):
            b=np.array([[0,0],[0,0]])
        else:
            b=A[Active_node,:][:,Active_node]
        #b=A[Active_node,:][:,Active_node]
        my_flag=pyflagser.flagser_unweighted(b, min_dimension=0, max_dimension=2, directed=False, coeff=2, approximation=None)
        x = my_flag["betti"]
            #print(x[0])
            #x_points.append(unique_list[k])
        b0_points.append(x[0])
        b1_points.append(x[1])
            #print(b)
            #print(x_points)
        n_active.clear()
    #print(b0_points)
    Flist_b0.append(b0_points)
    Flist_b1.append(b1_points)

Processing file 299 (100%)

In [73]:
Fx =np.array(Flist_b0)
Fx1 =np.array(Flist_b1)
n=len(Flist_b0[0])
print(q)
Feture=[]
for i in range(q):
    Feture.append("{}".format(i))
#Feture=list(range(9,17))
Fdata = pd.DataFrame(Fx, columns =Feture) 
Fdata.insert(loc=q,column='Class',value=Class)
Fdata.head(10)

12


0  1  2  3  4  5  6  7  8  9  10  11  Class
0  1  1  1  1  1  2  2  2  2  2   2   2      0
1  2  1  1  1  1  1  2  2  2  2   2   2      0
2  2  2  2  2  2  2  2  2  2  2   2   2      1
3  2  1  1  1  1  1  2  2  2  2   2   2      0
4  1  1  1  1  1  2  2  2  2  2   2   2      1
5  2  1  1  1  1  1  2  2  2  2   2   2      0
6  1  1  1  1  1  2  2  2  2  2   2   2      1
7  2  1  1  1  1  1  2  2  2  2   2   2      0
8  2  2  2  1  1  1  2  2  2  2   2   2      1
9  2  1  1  1  1  1  2  2  2  2   2   2      0

In [76]:
from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score
print("XGBoost")

feature=[]
for i in range(p*q):
    feature.append("{}".format(i))


X=data[feature] # Features
y=data['Class']  # Labels
#y=data["Class"].astype("category")
#print(X)

bst = XGBClassifier(n_estimators=200, max_depth=3, learning_rate=0.1)
scores = cross_val_score(bst, X, y, cv=10)
print("%0.3f accuracy with a standard deviation of %0.2f" % (scores.mean()*100, scores.std()))

XGBoost
96.333 accuracy with a standard deviation of 0.03


In [83]:
feature=[]
for i in range(p*q):
    feature.append("{}".format(i))

X=data[feature] # Features
y=data['Class']   # Labels


from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
# Don't cheat - fit only on training data
scaler.fit(X)  
#X_train = scaler.transform(X_train)  
# apply same transformation to test data
#X_test = scaler.transform(X_test)  

from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(50,),activation='logistic', learning_rate='constant', learning_rate_init=0.1, random_state=1, max_iter=1500, warm_start=True)

scores = cross_val_score(clf, X, y, cv=10)
print("%0.3f accuracy with a standard deviation of %0.2f" % (scores.mean()*100, scores.std()))

96.000 accuracy with a standard deviation of 0.04


In [48]:

print("XGBoost using only voltage")

feature=[]
for i in range(p):
    feature.append("{}".format(i))


X=Vdata[feature] # Features
y=Vdata['Class']  # Labels
#y=data["Class"].astype("category")
#print(X)

bst = XGBClassifier(n_estimators=200, max_depth=3, learning_rate=0.1)
scores = cross_val_score(bst, X, y, cv=10)
print("%0.3f accuracy with a standard deviation of %0.2f" % (scores.mean()*100, scores.std()))

XGBoost using only voltage
91.333 accuracy with a standard deviation of 0.06


In [74]:

print("XGBoost using only Brancj Flow")

feature=[]
for i in range(q):
    feature.append("{}".format(i))


X=Fdata[feature] # Features
y=Fdata['Class']  # Labels
#y=data["Class"].astype("category")
#print(X)

bst = XGBClassifier(n_estimators=200, max_depth=3, learning_rate=0.1)
scores = cross_val_score(bst, X, y, cv=10)
print("%0.3f accuracy with a standard deviation of %0.2f" % (scores.mean()*100, scores.std()))

XGBoost using only Brancj Flow
86.333 accuracy with a standard deviation of 0.05
