In [1]:
import os
import networkx as nx
import numpy as np
import pandas as pd
import math
import pyflagser

In [2]:
G=nx.read_gml("bus123Ex.gml")

In [3]:
G.nodes()

NodeView(('150', '150r', '149', '1', '2', '3', '7', '4', '5', '6', '8', '12', '9', '13', '9r', '14', '34', '18', '11', '10', '15', '16', '17', '19', '21', '20', '22', '23', '24', '25', '25r', '26', '28', '27', '31', '33', '29', '30', '250', '32', '35', '36', '40', '37', '38', '39', '41', '42', '43', '44', '45', '47', '46', '48', '49', '50', '51', '151', '52', '53', '54', '55', '57', '56', '58', '60', '59', '61', '62', '63', '64', '65', '66', '67', '68', '72', '97', '69', '70', '71', '73', '76', '74', '75', '77', '86', '78', '79', '80', '81', '82', '84', '83', '85', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '98', '99', '100', '450', '197', '101', '102', '105', '103', '104', '106', '108', '107', '109', '300', '110', '111', '112', '113', '114', '135', '152', '160r', '160', '61s', '300_open', '94_open', '610'))

In [4]:
G.edges

EdgeView([('150', '150r'), ('150r', '149'), ('149', '1'), ('1', '2'), ('1', '3'), ('1', '7'), ('3', '4'), ('3', '5'), ('7', '8'), ('5', '6'), ('8', '12'), ('8', '9'), ('8', '13'), ('9', '9r'), ('13', '34'), ('13', '18'), ('13', '152'), ('9r', '14'), ('14', '11'), ('14', '10'), ('34', '15'), ('18', '19'), ('18', '21'), ('18', '135'), ('15', '16'), ('15', '17'), ('19', '20'), ('21', '22'), ('21', '23'), ('23', '24'), ('23', '25'), ('25', '28'), ('25', '25r'), ('25r', '26'), ('26', '27'), ('26', '31'), ('28', '29'), ('27', '33'), ('31', '32'), ('29', '30'), ('30', '250'), ('35', '36'), ('35', '40'), ('35', '135'), ('36', '37'), ('36', '38'), ('40', '41'), ('40', '42'), ('38', '39'), ('42', '43'), ('42', '44'), ('44', '45'), ('44', '47'), ('45', '46'), ('47', '48'), ('47', '49'), ('49', '50'), ('50', '51'), ('51', '151'), ('151', '300_open'), ('52', '53'), ('52', '152'), ('53', '54'), ('54', '55'), ('54', '57'), ('54', '94_open'), ('55', '56'), ('57', '58'), ('57', '60'), ('58', '59'), ('6

In [5]:
A = nx.to_numpy_array(G)
print(A)

[[0. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [6]:
print(sum(sum(A))/2)

131.0


In [7]:
N=list(G.nodes)
print(N)
print(len(N))

['150', '150r', '149', '1', '2', '3', '7', '4', '5', '6', '8', '12', '9', '13', '9r', '14', '34', '18', '11', '10', '15', '16', '17', '19', '21', '20', '22', '23', '24', '25', '25r', '26', '28', '27', '31', '33', '29', '30', '250', '32', '35', '36', '40', '37', '38', '39', '41', '42', '43', '44', '45', '47', '46', '48', '49', '50', '51', '151', '52', '53', '54', '55', '57', '56', '58', '60', '59', '61', '62', '63', '64', '65', '66', '67', '68', '72', '97', '69', '70', '71', '73', '76', '74', '75', '77', '86', '78', '79', '80', '81', '82', '84', '83', '85', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '98', '99', '100', '450', '197', '101', '102', '105', '103', '104', '106', '108', '107', '109', '300', '110', '111', '112', '113', '114', '135', '152', '160r', '160', '61s', '300_open', '94_open', '610']
132


In [8]:
E=list(G.edges)
print(E)
print(len(E))

[('150', '150r'), ('150r', '149'), ('149', '1'), ('1', '2'), ('1', '3'), ('1', '7'), ('3', '4'), ('3', '5'), ('7', '8'), ('5', '6'), ('8', '12'), ('8', '9'), ('8', '13'), ('9', '9r'), ('13', '34'), ('13', '18'), ('13', '152'), ('9r', '14'), ('14', '11'), ('14', '10'), ('34', '15'), ('18', '19'), ('18', '21'), ('18', '135'), ('15', '16'), ('15', '17'), ('19', '20'), ('21', '22'), ('21', '23'), ('23', '24'), ('23', '25'), ('25', '28'), ('25', '25r'), ('25r', '26'), ('26', '27'), ('26', '31'), ('28', '29'), ('27', '33'), ('31', '32'), ('29', '30'), ('30', '250'), ('35', '36'), ('35', '40'), ('35', '135'), ('36', '37'), ('36', '38'), ('40', '41'), ('40', '42'), ('38', '39'), ('42', '43'), ('42', '44'), ('44', '45'), ('44', '47'), ('45', '46'), ('47', '48'), ('47', '49'), ('49', '50'), ('50', '51'), ('51', '151'), ('151', '300_open'), ('52', '53'), ('52', '152'), ('53', '54'), ('54', '55'), ('54', '57'), ('54', '94_open'), ('55', '56'), ('57', '58'), ('57', '60'), ('58', '59'), ('60', '61')

In [9]:
import pickle
with open('PartialObservdata.pkl', 'rb') as f:
    POData = pickle.load(f)
N_Senario=len(POData)
print(N_Senario)

5501


In [10]:
AverageVoltage=[]
def Average(lst):
    return sum(lst) / len(lst)
Voltage=POData[0]["Bus Voltages"]
for x, y in Voltage.items():
    AverageVoltage.append(Average(list(y)))
print(AverageVoltage)
AverageVoltage = [-1 if math.isnan(x) else x for x in AverageVoltage]
print(AverageVoltage)
print(len(AverageVoltage))

[0.9999921521557337, 0.9999893663650327, nan, nan, 0.33233953679734435, nan, 0.9860163947381686, 0.3295636682777559, 0.3293166448322464, nan, nan, 0.3312098278971435, 0.32338497859964704, 0.9767461195408749, 0.3233844869592422, 0.32283674691986225, nan, nan, nan, nan, nan, nan, nan, nan, 0.9693162948226569, nan, 0.3286985285889617, 0.968925277425361, 0.32124165055075987, nan, 0.6391356651368088, nan, 0.968399846169297, nan, nan, nan, 0.9682464235707172, nan, 0.9681642160385239, 0.3209263569349921, 0.9677464244331045, nan, nan, 0.3167326610461621, 0.327893579393088, nan, nan, nan, 0.3271039608435613, 0.9644419602932652, nan, nan, 0.3155673330922214, nan, 0.9630099439823997, nan, 0.9628595208871333, 0.9628595372114729, 0.9730165667639138, 0.9712088368404831, 0.9701117290129583, nan, nan, nan, 0.32822495828240944, nan, nan, 0.9608346257511707, nan, nan, 0.9572627202608764, nan, 0.9555798347535549, 0.9589240857235342, nan, 0.9585320124109602, 0.9581564360597149, 0.3122490542474168, 0.31180

In [11]:
BranchFlow=[]
Bflow=POData[0]["BranchFlow"]
for x, y in Bflow.items():
    BranchFlow.append(y)
print(BranchFlow)

BranchFlow = [-1 if math.isnan(x) else x for x in BranchFlow]
print(BranchFlow)
print(len(BranchFlow))

[518.9463274185551, nan, 518.9463274083047, nan, nan, 494.1979306385442, 18.832662176718273, 27.727231472812274, 491.03624713543496, 18.410639069464185, nan, 46.55765723304688, 472.49035926014994, 27.364765746117538, nan, nan, 283.2855858408923, 27.36476574683609, nan, 9.316768263417353, nan, 38.16709367929388, 43.799463621838896, nan, nan, 9.564243862318891, 18.633750572719826, 18.38793581123012, nan, nan, nan, 18.577244238669405, nan, 18.983336434492898, 9.31705239475981, nan, nan, 18.63361314418031, nan, 6.44547698836918, nan, 18.251182401941165, 105.0386789433635, nan, nan, nan, 9.646522396895993, 101.83960691017325, nan, nan, nan, 19.07149928918659, 86.24669956868244, nan, nan, nan, nan, nan, nan, 0.0, nan, 283.28558587487834, nan, 6.10106116973265, nan, nan, 3.1409991289978905, 18.774566219215654, nan, nan, 0.0016544608296345834, nan, 202.0072333224616, 1.342567048345087e-05, 52.86574453006657, 46.59918406170257, 35.17389297945738, 12.090578195748904, 57.93926372225504, 126.66122

In [12]:
F_voltage=[0.99,0.98,0.97,0.96,0.95,0.94,0.93,0.90,0.85,0.80,0.75,0.50,0.25,0,-1]
F_Flow=[300,200,175,150,125,100,75,50,30,15,10,0,-1]
p=len(F_voltage)
q=len(F_Flow)
print(p)
print(q)
print(p*q)

15
13
195


In [14]:
Class=[]
for i in range(1000):
    Class.append(POData[i]["NetOutage"])
#print(Class)
i=0
l=0
m=0
while i < len(Class):
    if Class[i] == 'No':
        l=l+1
        Class[i] = 0
    if Class[i] == 'Yes':
        m=m+1
        Class[i] = 1
    i += 1
#print(Class)
print(l)
print(m)

109
891


In [16]:
import time
start = time.time()
list_b0=[]
list_b1=[]
N_Senario=1000
for k in range(N_Senario):
    print("\rProcessing file {} ({}%)".format(k, 100*k//(N_Senario-1)), end='', flush=True)
    AverageVoltage=[]
    Voltage=POData[k]["Bus Voltages"]
    for x, y in Voltage.items():
        AverageVoltage.append(Average(list(y)))
    AverageVoltage = [-1 if math.isnan(x) else x for x in AverageVoltage]
    #print(AverageVoltage)
    BranchFlow=[]
    Bflow=POData[k]["BranchFlow"]
    for x, y in Bflow.items():
        BranchFlow.append(y)
    #print(BranchFlow)
    BranchFlow = [-1 if math.isnan(x) else x for x in BranchFlow]
    #print(BranchFlow)
    b0_points=[]
    b1_points=[]
    for p in range(len(F_voltage)):
        for q in range(len(F_Flow)):
            n_active = np.where(np.array(AverageVoltage) > F_voltage[p])[0].tolist()
            indices = np.where(np.array(BranchFlow) > F_Flow[q])[0].tolist()
            for s in indices:
                n_active.append(int(N.index(E[s][0])))
                n_active.append(int(N.index(E[s][1])))
            Active_node=np.unique(n_active)
            #print(Active_node)
            b=A[Active_node,:][:,Active_node]
            my_flag=pyflagser.flagser_unweighted(b, min_dimension=0, max_dimension=2, directed=False, coeff=2, approximation=None)
            x = my_flag["betti"]
            #print(x[0])
            #x_points.append(unique_list[k])
            b0_points.append(x[0])
            b1_points.append(x[1])
            #print(b)
            #print(x_points)
            n_active.clear()
    #print(b0_points)
    list_b0.append(b0_points)
    list_b1.append(b1_points)
end = time.time()
print("The time of execution of above program is :", (end-start) * 10**3, "ms")

Processing file 999 (100%)The time of execution of above program is : 65333.87494087219 ms


In [17]:
print(list_b0)

[[1, 2, 2, 2, 3, 4, 5, 6, 5, 8, 8, 9, 10, 1, 2, 2, 2, 3, 4, 5, 6, 5, 8, 8, 9, 10, 2, 2, 2, 2, 3, 4, 5, 6, 5, 7, 7, 8, 9, 14, 12, 12, 12, 12, 11, 9, 10, 8, 8, 8, 7, 7, 21, 19, 19, 19, 19, 18, 16, 13, 11, 9, 9, 8, 8, 21, 19, 19, 19, 19, 18, 16, 13, 11, 9, 9, 8, 8, 21, 19, 19, 19, 19, 18, 16, 13, 11, 9, 9, 8, 8, 21, 19, 19, 19, 19, 18, 16, 13, 11, 9, 9, 8, 8, 21, 19, 19, 19, 19, 18, 16, 13, 11, 9, 9, 8, 8, 21, 19, 19, 19, 19, 18, 16, 13, 11, 9, 9, 8, 8, 21, 19, 19, 19, 19, 18, 16, 13, 11, 9, 9, 8, 8, 22, 20, 20, 20, 20, 19, 17, 14, 12, 9, 9, 8, 8, 37, 35, 35, 35, 35, 33, 31, 26, 23, 10, 10, 9, 9, 37, 35, 35, 35, 35, 33, 31, 26, 23, 10, 10, 9, 9, 37, 35, 35, 35, 35, 33, 31, 26, 23, 10, 10, 9, 9], [1, 1, 1, 2, 2, 3, 5, 6, 6, 6, 8, 9, 10, 2, 1, 1, 2, 2, 3, 5, 6, 6, 6, 7, 8, 9, 21, 20, 20, 19, 19, 19, 17, 15, 12, 11, 9, 8, 8, 21, 20, 20, 19, 19, 19, 17, 15, 12, 11, 9, 8, 8, 21, 20, 20, 19, 19, 19, 17, 15, 12, 11, 9, 8, 8, 21, 20, 20, 19, 19, 19, 17, 15, 12, 11, 9, 8, 8, 21, 20, 20, 19, 19, 19

In [19]:
p=len(F_voltage)
q=len(F_Flow)
x =np.array(list_b0)
x1 =np.array(list_b1)
n=len(list_b0[0])
print(n)
Feture=[]
for i in range(p*q):
    Feture.append("{}".format(i))
#Feture=list(range(9,17))
data = pd.DataFrame(x, columns =Feture) 
data.insert(loc=p*q,column='Class',value=Class)
data.head(10)

195


0  1  2  3  4  5  6  7  8  9  ...  186  187  188  189  190  191  192  193  \
0  1  2  2  2  3  4  5  6  5  8  ...   35   33   31   26   23   10   10    9   
1  1  1  1  2  2  3  5  6  6  6  ...   35   35   32   30   24   20   10    9   
2  1  1  2  2  3  4  5  6  5  8  ...   35   33   31   26   23   10   10   10   
3  1  1  2  2  2  4  5  6  5  8  ...   35   35   31   28   23   10   10   10   
4  1  1  1  1  2  2  4  5  6  6  ...   35   35   34   31   26   21   10   10   
5  2  1  1  1  1  2  2  2  2  4  ...   37   37   34   34   33   24   24   13   
6  5  3  3  3  4  4  4  5  6  6  ...   35   35   34   31   27   23   12    9   
7  2  1  1  1  1  1  2  2  2  3  ...   37   37   34   34   33   26   25   25   
8  3  2  1  1  1  1  2  2  2  3  ...   37   37   35   34   33   26   26   25   
9  5  3  3  3  3  4  4  4  4  5  ...   34   32   31   31   30   23   23   23   

   194  Class  
0    9      0  
1    9      0  
2    9      0  
3    9      0  
4    9      0  
5    9      1  
6    9      1  
7    9      1  
8    9      1  
9    9      1  

[10 rows x 196 columns]

In [28]:
start = time.time()
Vlist_b0=[]
Vlist_b1=[]
N_Senario=1000
for k in range(N_Senario):
    print("\rProcessing file {} ({}%)".format(k, 100*k//(N_Senario-1)), end='', flush=True)
    AverageVoltage=[]
    Voltage=POData[k]["Bus Voltages"]
    for x, y in Voltage.items():
        AverageVoltage.append(Average(list(y)))
    AverageVoltage = [-1 if math.isnan(x) else x for x in AverageVoltage]
    b0_points=[]
    b1_points=[]
    for p in range(len(F_voltage)):
        n_active = np.where(np.array(AverageVoltage) > F_voltage[p])[0].tolist()
        Active_node=np.unique(n_active)
            #print(Active_node)
        b=A[Active_node,:][:,Active_node]
        my_flag=pyflagser.flagser_unweighted(b, min_dimension=0, max_dimension=2, directed=False, coeff=2, approximation=None)
        x = my_flag["betti"]
            #print(x[0])
            #x_points.append(unique_list[k])
        b0_points.append(x[0])
        b1_points.append(x[1])
            #print(b)
            #print(x_points)
        n_active.clear()
    #print(b0_points)
    Vlist_b0.append(b0_points)
    Vlist_b1.append(b1_points)

end = time.time()
print("The time of execution of above program is :", (end-start) * 10**3, "ms")

Processing file 999 (100%)The time of execution of above program is : 5089.169979095459 ms


In [30]:
Vx =np.array(Vlist_b0)
Vx1 =np.array(Vlist_b1)
n=len(Vlist_b0[0])
p=len(F_voltage)
print(p)
Feture=[]
for i in range(p):
    Feture.append("{}".format(i))
#Feture=list(range(9,17))
Vdata = pd.DataFrame(Vx, columns =Feture) 
Vdata.insert(loc=p,column='Class',value=Class)
Vdata.head(10)

15


0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  Class
0  1   2   4  16  23  23  23  23  23  23  23  24  42  42  42      0
1  2   4  23  23  23  23  23  23  23  23  23  24  42  42  42      0
2  1   2   4  15  22  22  22  22  22  22  22  23  41  41  42      0
3  1   2   5  15  22  22  22  22  22  22  22  23  41  41  42      0
4  2  16  21  21  21  21  21  21  21  21  21  22  40  40  42      0
5  2   5  11  11  11  11  11  11  11  11  11  12  23  40  42      1
6  5  21  21  21  21  21  21  21  21  21  21  22  40  42  42      1
7  2   8  11  11  11  11  11  11  11  11  11  12  22  22  42      1
8  3   8  11  11  11  11  11  11  11  11  11  12  22  22  42      1
9  2   5  12  12  12  12  12  12  12  12  12  13  24  24  42      1

In [32]:
start = time.time()
Flist_b0=[]
Flist_b1=[]
N_Senario=1000
for k in range(N_Senario):
    print("\rProcessing file {} ({}%)".format(k, 100*k//(N_Senario-1)), end='', flush=True)
    BranchFlow=[]
    Bflow=POData[k]["BranchFlow"]
    for x, y in Bflow.items():
        BranchFlow.append(y)
    #print(BranchFlow)
    BranchFlow = [-1 if math.isnan(x) else x for x in BranchFlow]
    #print(BranchFlow)
    b0_points=[]
    b1_points=[]

    for q in range(len(F_Flow)):
        indices = np.where(np.array(BranchFlow) > F_Flow[q])[0].tolist()

        for s in indices:
            n_active.append(int(N.index(E[s][0])))
            n_active.append(int(N.index(E[s][1])))
        Active_node=np.unique(n_active)
        if (len(Active_node)==0):
            b=np.array([[0,0],[0,0]])
        else:
            b=A[Active_node,:][:,Active_node]
        #b=A[Active_node,:][:,Active_node]
        my_flag=pyflagser.flagser_unweighted(b, min_dimension=0, max_dimension=2, directed=False, coeff=2, approximation=None)
        x = my_flag["betti"]
            #print(x[0])
            #x_points.append(unique_list[k])
        b0_points.append(x[0])
        b1_points.append(x[1])
            #print(b)
            #print(x_points)
        n_active.clear()
    #print(b0_points)
    Flist_b0.append(b0_points)
    Flist_b1.append(b1_points)
end = time.time()
print("The time of execution of above program is :", (end-start) * 10**3, "ms")

Processing file 999 (100%)The time of execution of above program is : 5068.742036819458 ms


In [33]:
Fx =np.array(Flist_b0)
Fx1 =np.array(Flist_b1)
n=len(Flist_b0[0])
q=len(F_Flow)
print(q)
Feture=[]
for i in range(q):
    Feture.append("{}".format(i))
#Feture=list(range(9,17))
Fdata = pd.DataFrame(Fx, columns =Feture) 
Fdata.insert(loc=q,column='Class',value=Class)
Fdata.head(10)

13


0  1  2  3  4  5  6  7  8  9  10  11  12  Class
0  1  2  2  2  3  4  5  6  5  8   8   9  10      0
1  1  1  1  2  2  3  5  6  6  6   8   9  10      0
2  1  1  2  2  3  4  5  6  5  8   8   9  10      0
3  1  1  2  2  2  4  5  6  5  8   8   9  10      0
4  1  1  1  1  2  2  4  5  6  6   8   9  10      0
5  2  1  1  1  1  2  2  2  2  4   4  10  10      1
6  2  1  1  1  2  2  4  5  6  6   8   9  10      1
7  2  1  1  1  1  1  2  2  2  3   3   4  10      1
8  2  1  1  1  1  1  2  2  2  3   3   4  10      1
9  3  3  3  3  3  4  4  4  4  5   5   7  10      1

In [23]:
from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score
print("XGBoost")

feature=[]
for i in range(p*q):
    feature.append("{}".format(i))


X=data[feature] # Features
y=data['Class']  # Labels
#y=data["Class"].astype("category")
#print(X)

bst = XGBClassifier(n_estimators=200, max_depth=3, learning_rate=0.1)
scores = cross_val_score(bst, X, y, cv=10)
print("%0.3f accuracy with a standard deviation of %0.2f" % (scores.mean()*100, scores.std()))

XGBoost
98.400 accuracy with a standard deviation of 0.01


In [27]:
feature=[]
for i in range(p*q):
    feature.append("{}".format(i))

X=data[feature] # Features
y=data['Class']   # Labels


from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
# Don't cheat - fit only on training data
scaler.fit(X)  
#X_train = scaler.transform(X_train)  
# apply same transformation to test data
#X_test = scaler.transform(X_test)  

from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(50,),activation='logistic', learning_rate='constant', learning_rate_init=0.1, random_state=1, max_iter=2000, warm_start=True)

scores = cross_val_score(clf, X, y, cv=10)
print("%0.3f accuracy with a standard deviation of %0.2f" % (scores.mean()*100, scores.std()))

97.600 accuracy with a standard deviation of 0.02


In [31]:

print("XGBoost using only voltage")

feature=[]
for i in range(p):
    feature.append("{}".format(i))


X=Vdata[feature] # Features
y=Vdata['Class']  # Labels
#y=data["Class"].astype("category")
#print(X)

bst = XGBClassifier(n_estimators=200, max_depth=3, learning_rate=0.1)
scores = cross_val_score(bst, X, y, cv=10)
print("%0.3f accuracy with a standard deviation of %0.2f" % (scores.mean()*100, scores.std()))

XGBoost using only voltage
97.200 accuracy with a standard deviation of 0.02


In [35]:

print("XGBoost using only Brancj Flow")

feature=[]
for i in range(q):
    feature.append("{}".format(i))


X=Fdata[feature] # Features
y=Fdata['Class']  # Labels
#y=data["Class"].astype("category")
#print(X)

bst = XGBClassifier(n_estimators=200, max_depth=3, learning_rate=0.1)
scores = cross_val_score(bst, X, y, cv=10)
print("%0.3f accuracy with a standard deviation of %0.2f" % (scores.mean()*100, scores.std()))

XGBoost using only Brancj Flow
97.200 accuracy with a standard deviation of 0.02
