In [2]:
import os
import networkx as nx
import numpy as np
import pandas as pd
import math
import pyflagser

In [3]:
G=nx.read_gml("busLVNet.gml")

In [4]:
G.nodes()

NodeView(('p1', 'p2', 'p3', 'p7', 'p6', 'p11', 'p27', 'p44', 'p45', 'p62', 'p10', 'p81', 'p97', 'p116', 'p117', 'p134', 'p12', 'p13', 'p14', 'p15', 'p16', 'p17', 'p18', 'p19', 'p20', 'p21', 'p22', 'p23', 'p24', 'p25', 'p26', 'p28', 'p29', 'p30', 'p31', 'p32', 'p33', 'p34', 'p35', 'p36', 'p37', 'p38', 'p39', 'p40', 'p41', 'p42', 'p43', 'p46', 'p47', 'p48', 'p49', 'p50', 'p51', 'p52', 'p53', 'p54', 'p55', 'p56', 'p57', 'p58', 'p59', 'p60', 'p61', 'p63', 'p64', 'p65', 'p66', 'p67', 'p68', 'p69', 'p70', 'p71', 'p72', 'p73', 'p74', 'p75', 'p76', 'p77', 'p78', 'p79', 'p80', 'p82', 'p83', 'p84', 'p85', 'p86', 'p87', 'p88', 'p89', 'p90', 'p91', 'p92', 'p93', 'p94', 'p95', 'p96', 'p98', 'p99', 'p100', 'p101', 'p102', 'p103', 'p104', 'p105', 'p106', 'p107', 'p108', 'p109', 'p110', 'p111', 'p112', 'p113', 'p114', 'p115', 'p118', 'p119', 'p120', 'p121', 'p122', 'p123', 'p124', 'p125', 'p126', 'p127', 'p128', 'p129', 'p130', 'p131', 'p132', 'p133', 'p135', 'p136', 'p137', 'p138', 'p139', 'p140', 'p

In [5]:
G.edges

EdgeView([('p1', 'p2'), ('p2', 'p3'), ('p2', 'p7'), ('p3', 'p4'), ('p7', 'p8'), ('p6', 'p11'), ('p6', 'p27'), ('p6', 'p44'), ('p6', 'p5'), ('p11', 'p12'), ('p27', 'p28'), ('p44', 'p45'), ('p44', 'p62'), ('p45', 'p46'), ('p62', 'p63'), ('p10', 'p81'), ('p10', 'p97'), ('p10', 'p116'), ('p10', 'p9'), ('p81', 'p82'), ('p97', 'p98'), ('p116', 'p117'), ('p116', 'p134'), ('p117', 'p118'), ('p134', 'p135'), ('p12', 'p13'), ('p13', 'p14'), ('p13', 'p15'), ('p14', 's192'), ('p15', 'p16'), ('p15', 'p18'), ('p16', 'p17'), ('p16', 's238'), ('p17', 's180'), ('p18', 'p19'), ('p18', 'p20'), ('p19', 's171'), ('p20', 'p21'), ('p20', 'p23'), ('p21', 'p22'), ('p21', 's168'), ('p22', 's207'), ('p23', 'p24'), ('p23', 'p25'), ('p24', 's155'), ('p25', 'p26'), ('p26', 's157'), ('p28', 'p29'), ('p29', 'p30'), ('p29', 'p31'), ('p30', 's187'), ('p31', 'p32'), ('p31', 'p33'), ('p32', 's191'), ('p33', 'p34'), ('p33', 'p35'), ('p34', 's221'), ('p35', 'p36'), ('p35', 'p37'), ('p36', 's170'), ('p37', 'p38'), ('p37', '

In [6]:
A = nx.to_numpy_array(G)
print(A)
print(sum(sum(A))/2)

[[0. 1. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
460.0


In [7]:
N=list(G.nodes)
print(len(N))

390


In [8]:
E=list(G.edges)
print(len(E))

460


In [9]:
import pickle
with open('PartialObservdata.pkl', 'rb') as f:
    POData = pickle.load(f)
N_Senario=len(POData)
print(N_Senario)

4501


In [10]:
AverageVoltage=[]
def Average(lst):
    return sum(lst) / len(lst)
Voltage=POData[0]["Bus Voltages"]
for x, y in Voltage.items():
    AverageVoltage.append(Average(list(y)))
print(AverageVoltage)
AverageVoltage = [-1 if math.isnan(x) else x for x in AverageVoltage]
print(AverageVoltage)
print(len(AverageVoltage))

[1.049816387726233, 1.0498042077250493, 1.049798154151289, 1.049798076085669, 1.0265197116396318, 1.026473476610956, nan, nan, nan, 1.0264536773749964, nan, nan, nan, nan, nan, 1.026162184854818, nan, nan, nan, 1.0240766176281892, nan, nan, nan, 1.024014564221284, 1.0239809869118461, 1.023958067001514, nan, 1.0239608269929859, nan, 1.0239508546179785, nan, nan, nan, 1.0243735372314073, 1.024307102566442, 1.0242982198330346, 1.024240814426398, nan, 1.024190942661704, 1.0241808762933686, 1.0241511293903676, nan, nan, nan, nan, nan, 1.024100316111462, nan, nan, nan, nan, 1.0240128709323315, 1.0239478414536476, 1.0239395592180278, nan, nan, 1.0238146980500404, 1.0238060754512592, 1.0238558549605956, 1.0238468886237069, nan, nan, nan, 1.0264536348544755, 1.0243213042126091, 1.024313298783906, nan, nan, 1.0241755337051108, 1.024171896286677, nan, nan, nan, nan, nan, 1.0240208213470536, 1.0240058567269026, nan, nan, 1.0239933805998105, 1.0239843229645864, 1.0261788158522893, nan, 1.0238332298

In [11]:
BranchFlow=[]
Bflow=POData[0]["BranchFlow"]
for x, y in Bflow.items():
    BranchFlow.append(y)
print(BranchFlow)

BranchFlow = [-1 if math.isnan(x) else x for x in BranchFlow]
print(BranchFlow)
print(len(BranchFlow))

[123.60282034910647, nan, 62.146751122593656, 61.481662031418104, nan, 267.1042718260833, nan, nan, 1024.689046727278, nan, 241.50351265343934, nan, nan, 270.4166077300051, 245.742831650176, nan, 285.33111406343147, 481.0904765162314, nan, 269.63453455940316, nan, nan, nan, 230.3049319875705, 250.82503489742285, nan, nan, nan, 26.56194833694587, nan, 151.86037094451433, 21.456098879195746, nan, nan, nan, nan, 27.438324483026125, nan, nan, 36.96721891529941, nan, 36.98472036729819, nan, 28.861658142575564, 29.465799045086495, nan, 28.898908961261586, 241.50351225178142, nan, 216.7672452099314, nan, nan, 191.12916596170953, 25.68155764183597, nan, nan, nan, 29.140255119706296, nan, 29.15890145386072, nan, 90.6888054319437, nan, nan, nan, 33.56602096300133, 29.53941916466954, nan, 27.879999451810033, 27.897945199126195, 270.41660728922005, nan, nan, 25.646372747347282, 28.792945457139762, 216.4654876303271, nan, nan, 192.6409632950306, nan, 119.79688226470535, 72.88965106795474, 72.164417

In [12]:
F_voltage=[0.99,0.98,0.97,0.96,0.95,0.94,0.93,0.90,0.85,0.80,0.75,0.50,0.25,0,-1]
F_Flow=[300,200,175,150,125,100,75,50,30,15,10,0,-1]
p=len(F_voltage)
q=len(F_Flow)
print(p)
print(q)
print(p*q)

15
13
195


In [14]:
Class=[]
for i in range(300):
    Class.append(POData[i]["NetOutage"])
#print(Class)
i=0
l=0
m=0
while i < len(Class):
    if Class[i] == 'No':
        l=l+1
        Class[i] = 0
    if Class[i] == 'Yes':
        m=m+1
        Class[i] = 1
    i += 1
#print(Class)
#print(l)
#print(m)

In [15]:
import time
start = time.time()
list_b0=[]
list_b1=[]
N_Senario=300
for k in range(N_Senario):
    print("\rProcessing file {} ({}%)".format(k, 100*k//(N_Senario-1)), end='', flush=True)
    AverageVoltage=[]
    Voltage=POData[k]["Bus Voltages"]
    for x, y in Voltage.items():
        AverageVoltage.append(Average(list(y)))
    AverageVoltage = [-1 if math.isnan(x) else x for x in AverageVoltage]
    #print(AverageVoltage)
    BranchFlow=[]
    Bflow=POData[k]["BranchFlow"]
    for x, y in Bflow.items():
        BranchFlow.append(y)
    #print(BranchFlow)
    BranchFlow = [-1 if math.isnan(x) else x for x in BranchFlow]
    #print(BranchFlow)
    b0_points=[]
    b1_points=[]
    for p in range(len(F_voltage)):
        for q in range(len(F_Flow)):
            n_active = np.where(np.array(AverageVoltage) > F_voltage[p])[0].tolist()
            indices = np.where(np.array(BranchFlow) > F_Flow[q])[0].tolist()
            for s in indices:
                n_active.append(int(N.index(E[s][0])))
                n_active.append(int(N.index(E[s][1])))
            Active_node=np.unique(n_active)
            #print(Active_node)
            b=A[Active_node,:][:,Active_node]
            my_flag=pyflagser.flagser_unweighted(b, min_dimension=0, max_dimension=2, directed=False, coeff=2, approximation=None)
            x = my_flag["betti"]
            #print(x[0])
            #x_points.append(unique_list[k])
            b0_points.append(x[0])
            b1_points.append(x[1])
            #print(b)
            #print(x_points)
            n_active.clear()
    #print(b0_points)
    list_b0.append(b0_points)
    list_b1.append(b1_points)
end = time.time()
print("The time of execution of above program is :", (end-start) * 10**3, "ms")

Processing file 299 (100%)The time of execution of above program is : 79191.49684906006 ms


In [16]:
p=len(F_voltage)
q=len(F_Flow)
x =np.array(list_b0)
x1 =np.array(list_b1)
n=len(list_b0[0])
print(n)
Feture=[]
for i in range(p*q):
    Feture.append("{}".format(i))
#Feture=list(range(9,17))
data = pd.DataFrame(x, columns =Feture) 
data.insert(loc=p*q,column='Class',value=Class)
data.head(20)

195


0   1   2   3   4   5   6   7   8   9  ...  186  187  188  189  190  191  \
0   56  44  39  38  37  30  24  18  14   5  ...   37   30   24   18   14    5   
1   61  55  48  44  39  38  30  21  18   5  ...   39   38   30   21   18    5   
2   61  55  48  44  39  38  30  21  18   5  ...   39   38   30   21   18    5   
3   61  56  55  48  44  41  37  27  20  11  ...   44   41   37   27   20   11   
4   53  41  38  38  37  29  23  17  13   5  ...   40   31   25   18   14    6   
5   57  44  41  40  39  33  25  20  18   5  ...   39   33   25   20   18    5   
6   56  39  38  37  37  27  22  16  12   5  ...   41   31   26   20   16    8   
7   57  46  43  40  39  33  26  18  15   5  ...   38   32   25   17   14    5   
8   58  45  43  42  39  33  29  21  13   6  ...   39   33   28   20   13    6   
9   50  42  38  35  29  24  23  18  12   8  ...   35   29   28   19   14    9   
10  61  55  48  44  39  38  30  21  18   5  ...   39   38   30   21   18    5   
11  49  42  40  38  33  28  22  16  10   6  ...   39   33   27   21   15    8   
12  34  30  28  28  26  26  23  16  14  11  ...   33   27   24   20   15    9   
13  53  46  44  39  36  29  26  19  12   6  ...   38   32   29   22   15    6   
14  60  55  54  49  38  37  33  23  19  14  ...   38   37   33   23   19   14   
15  64  50  44  41  36  35  31  25  13  10  ...   36   35   31   25   13   10   
16   1   1   1   1   1   1   1   1   1   1  ...   76   76   76   76   76   76   
17   1   1   1   1   1   1   1   1   1   1  ...   76   76   76   76   76   76   
18   1   1   1   1   1   1   1   1   1   1  ...   76   76   76   76   76   76   
19  61  55  48  44  39  38  30  21  18   5  ...   39   38   30   21   18    5   

    192  193  194  Class  
0     5    4    4      0  
1     5    4    4      0  
2     5    4    4      0  
3     6    4    4      0  
4     6    4    4      0  
5     5    4    4      0  
6     8    7    4      0  
7     5    4    4      0  
8     5    4    4      0  
9     9    6    4      1  
10    5    4    4      0  
11    7    4    4      0  
12    8    4    4      0  
13    5    4    4      0  
14   13    4    4      0  
15   10    4    4      0  
16   76   76    4      1  
17   76   76    4      1  
18   76   76    4      1  
19    5    4    4      0  

[20 rows x 196 columns]

In [17]:
start = time.time()
Vlist_b0=[]
Vlist_b1=[]
N_Senario=300
for k in range(N_Senario):
    print("\rProcessing file {} ({}%)".format(k, 100*k//(N_Senario-1)), end='', flush=True)
    AverageVoltage=[]
    Voltage=POData[k]["Bus Voltages"]
    for x, y in Voltage.items():
        AverageVoltage.append(Average(list(y)))
    AverageVoltage = [-1 if math.isnan(x) else x for x in AverageVoltage]
    b0_points=[]
    b1_points=[]
    for p in range(len(F_voltage)):
        n_active = np.where(np.array(AverageVoltage) > F_voltage[p])[0].tolist()
        Active_node=np.unique(n_active)
            #print(Active_node)
        b=A[Active_node,:][:,Active_node]
        my_flag=pyflagser.flagser_unweighted(b, min_dimension=0, max_dimension=2, directed=False, coeff=2, approximation=None)
        x = my_flag["betti"]
            #print(x[0])
            #x_points.append(unique_list[k])
        b0_points.append(x[0])
        b1_points.append(x[1])
            #print(b)
            #print(x_points)
        n_active.clear()
    #print(b0_points)
    Vlist_b0.append(b0_points)
    Vlist_b1.append(b1_points)

end = time.time()
print("The time of execution of above program is :", (end-start) * 10**3, "ms")

Processing file 299 (100%)The time of execution of above program is : 2758.9058876037598 ms


In [18]:
Vx =np.array(Vlist_b0)
Vx1 =np.array(Vlist_b1)
n=len(Vlist_b0[0])
p=len(F_voltage)
print(p)
Feture=[]
for i in range(p):
    Feture.append("{}".format(i))
#Feture=list(range(9,17))
Vdata = pd.DataFrame(Vx, columns =Feture) 
Vdata.insert(loc=p,column='Class',value=Class)
Vdata.head(20)

15


0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  Class
0   76  76  76  76  76  76  76  76  76  76  76  76  76  76  76      0
1   76  76  76  76  76  76  76  76  76  76  76  76  76  76  76      0
2   76  76  76  76  76  76  76  76  76  76  76  76  76  76  76      0
3   76  76  76  76  76  76  76  76  76  76  76  76  76  76  76      0
4   73  75  75  75  75  75  75  75  75  75  75  75  75  75  76      0
5   76  76  76  76  76  76  76  76  76  76  76  76  76  76  76      0
6   74  74  73  74  74  74  74  74  74  74  74  74  74  74  76      0
7   76  76  76  76  76  76  76  76  76  76  76  76  76  76  76      0
8   76  76  76  76  76  76  76  76  76  76  76  76  76  76  76      0
9   62  67  69  70  69  69  70  72  73  73  73  73  73  73  76      1
10  76  76  76  76  76  76  76  76  76  76  76  76  76  76  76      0
11  67  74  76  76  76  76  76  76  76  76  76  76  76  76  76      0
12  16  16  20  26  34  46  67  76  76  76  76  76  76  76  76      0
13  71  74  76  76  76  76  76  76  76  76  76  76  76  76  76      0
14  75  76  76  76  76  76  76  76  76  76  76  76  76  76  76      0
15  75  76  76  76  76  76  76  76  76  76  76  76  76  76  76      0
16   1   1   1   1   1   1   1   1   1   1   1   1   1   1  76      1
17   1   1   1   1   1   1   1   1   1   1   1   1   1   1  76      1
18   1   1   1   1   1   1   1   1   1   1   1   1   1   1  76      1
19  76  76  76  76  76  76  76  76  76  76  76  76  76  76  76      0

In [19]:
start = time.time()
Flist_b0=[]
Flist_b1=[]
N_Senario=300
for k in range(N_Senario):
    print("\rProcessing file {} ({}%)".format(k, 100*k//(N_Senario-1)), end='', flush=True)
    BranchFlow=[]
    Bflow=POData[k]["BranchFlow"]
    for x, y in Bflow.items():
        BranchFlow.append(y)
    #print(BranchFlow)
    BranchFlow = [-1 if math.isnan(x) else x for x in BranchFlow]
    #print(BranchFlow)
    b0_points=[]
    b1_points=[]

    for q in range(len(F_Flow)):
        indices = np.where(np.array(BranchFlow) > F_Flow[q])[0].tolist()

        for s in indices:
            n_active.append(int(N.index(E[s][0])))
            n_active.append(int(N.index(E[s][1])))
        Active_node=np.unique(n_active)
        if (len(Active_node)==0):
            b=np.array([[0,0],[0,0]])
        else:
            b=A[Active_node,:][:,Active_node]
        #b=A[Active_node,:][:,Active_node]
        my_flag=pyflagser.flagser_unweighted(b, min_dimension=0, max_dimension=2, directed=False, coeff=2, approximation=None)
        x = my_flag["betti"]
            #print(x[0])
            #x_points.append(unique_list[k])
        b0_points.append(x[0])
        b1_points.append(x[1])
            #print(b)
            #print(x_points)
        n_active.clear()
    #print(b0_points)
    Flist_b0.append(b0_points)
    Flist_b1.append(b1_points)
end = time.time()
print("The time of execution of above program is :", (end-start) * 10**3, "ms")

Processing file 299 (100%)The time of execution of above program is : 4498.739957809448 ms


In [20]:
Fx =np.array(Flist_b0)
Fx1 =np.array(Flist_b1)
n=len(Flist_b0[0])
q=len(F_Flow)
print(q)
Feture=[]
for i in range(q):
    Feture.append("{}".format(i))
#Feture=list(range(9,17))
Fdata = pd.DataFrame(Fx, columns =Feture) 
Fdata.insert(loc=q,column='Class',value=Class)
Fdata.head(10)

13


0   1   2   3   4   5   6   7   8   9  10  11  12  Class
0  32  36  40  43  44  43  40  32  21   9   9   8   8      0
1  29  34  36  36  40  43  43  34  31   9   9   8   8      0
2  29  34  36  36  40  43  43  34  31   9   9   8   8      0
3  29  32  33  36  36  41  44  39  30  13   9   8   8      0
4  32  36  39  41  43  43  37  31  21   9   9   8   8      0
5  31  36  38  42  43  40  37  31  21   9   9   8   8      0
6  31  34  38  41  42  39  37  30  19  10  10   8   8      0
7  30  35  38  42  43  43  38  32  20  10  10   9   8      0
8  32  36  39  43  41  42  39  33  20  10   9   9   8      0
9  32  36  39  40  36  36  35  26  19  10  10  10   8      1

In [21]:
import time
start = time.time()
from xgboost import XGBClassifier
from sklearn.model_selection import cross_val_score
print("XGBoost")

feature=[]
for i in range(p*q):
    feature.append("{}".format(i))


X=data[feature] # Features
y=data['Class']  # Labels
#y=data["Class"].astype("category")
#print(X)

bst = XGBClassifier(n_estimators=200, max_depth=2, learning_rate=0.1,subsample=0.9)
scores = cross_val_score(bst, X, y, cv=10)
print("%0.3f accuracy with a standard deviation of %0.2f" % (scores.mean()*100, scores.std()))
end = time.time()
print("The time of execution of above program is :", (end-start), "S")

XGBoost
92.000 accuracy with a standard deviation of 0.03
The time of execution of above program is : 1.563283920288086 S


In [22]:
feature=[]
for i in range(p*q):
    feature.append("{}".format(i))

X=data[feature] # Features
y=data['Class']   # Labels


from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
# Don't cheat - fit only on training data
scaler.fit(X)  
#X_train = scaler.transform(X_train)  
# apply same transformation to test data
#X_test = scaler.transform(X_test)  

from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(solver='adam', alpha=1e-5, hidden_layer_sizes=(100,),activation='logistic', learning_rate='constant', learning_rate_init=0.01, random_state=1, max_iter=3000, warm_start=True)

scores = cross_val_score(clf, X, y, cv=10)
print("%0.3f accuracy with a standard deviation of %0.2f" % (scores.mean()*100, scores.std()))

91.333 accuracy with a standard deviation of 0.02


In [23]:
print("XGBoost using only voltage")

feature=[]
for i in range(p):
    feature.append("{}".format(i))


X=Vdata[feature] # Features
y=Vdata['Class']  # Labels
#y=data["Class"].astype("category")
#print(X)

bst = XGBClassifier(n_estimators=200, max_depth=3, learning_rate=0.1,subsample=0.9)
scores = cross_val_score(bst, X, y, cv=10)
print("%0.3f accuracy with a standard deviation of %0.2f" % (scores.mean()*100, scores.std()))

XGBoost using only voltage
91.000 accuracy with a standard deviation of 0.05


In [24]:
print("XGBoost using only Branch Flow")

feature=[]
for i in range(q):
    feature.append("{}".format(i))


X=Fdata[feature] # Features
y=Fdata['Class']  # Labels
#y=data["Class"].astype("category")
#print(X)

bst = XGBClassifier(n_estimators=200, max_depth=3, learning_rate=0.1,subsample=0.9)
scores = cross_val_score(bst, X, y, cv=10)
print("%0.3f accuracy with a standard deviation of %0.2f" % (scores.mean()*100, scores.std()))

XGBoost using only Branch Flow
91.000 accuracy with a standard deviation of 0.03
